# Generated by Django 5.0.4 on 2024-05-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_loss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightlist',
            name='dateOfMarking',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='weightlist',
            name='weight',
            field=models.FloatField(),
        ),
    ]
